services:
  postgres:
    image: postgres:latest
    container_name: postgresql
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
