spring.application.name=spring-batch-demo

spring.datasource.jdbcUrl=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.business.datasource.jdbcUrl=jdbc:postgresql://localhost:5432/testdb
spring.business.datasource.driverClassName=org.postgresql.Driver
spring.business.datasource.username=test
spring.business.datasource.password=test

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.continue-on-error=true

# JDBC SQL logging
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

# JPA SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

logging.level.org.springframework.batch=INFO

# Actuator
management.health.db.enabled=false

# Micrometer / Prometheus Pushgateway
management.prometheus.metrics.export.pushgateway.enabled=true
management.prometheus.metrics.export.pushgateway.base-url=http://localhost:9091
management.prometheus.metrics.export.pushgateway.job=spring-batch-demo
management.prometheus.metrics.export.pushgateway.push-rate=15s
management.prometheus.metrics.export.pushgateway.shutdown-operation=post