spring.application.name=spring-batch-demo

spring.datasource.jdbcUrl=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.business.datasource.jdbcUrl=jdbc:postgresql://localhost:5432/testdb
spring.business.datasource.driverClassName=org.postgresql.Driver
spring.business.datasource.username=test
spring.business.datasource.password=test